.github/workflows/pr.yaml
.github/workflows/publish.yaml

Signed-off-by: Ievgenii Shepeliuk <ievgenii.shepeliuk@gig.com>

feat: publish opa bundles

---

.github/workflows/orch-asset-registry.yaml
.github/workflows/orch-deploy.yaml

Signed-off-by: Ievgenii Shepeliuk <ievgenii.shepeliuk@gig.com>

feat: dedicated asset registry branch

---

.github/workflows/orch-update.yaml

Tested on https://github.com/GiGInnovationLabs/orch-workflow-test

fix: checkout concurrency

---

.github/workflows/pr.yaml

feat: upgrade to support net 8

---

.github/workflows/orch-asset-registry.yaml
.github/workflows/pr.yaml

feat: update action steps version

---

.github/workflows/pr.yaml

fix: update editorconfigchecker condition

---

.github/workflows/pr.yaml

fix: update gh actions pin condition

---

.github/workflows/analysis.yaml
.github/workflows/pr.yaml

feat: added test coverage

---

.github/workflows/analysis.yaml
.github/workflows/pr.yaml

feat: updated workflows

---

.github/workflows/pr.yaml

feat: added retry and timeout in checking quality gate

---

.github/workflows/orch-pr.yaml

fix: env check as a diff job

---

.github/workflows/analysis.yaml
.github/workflows/pr.yaml

feat: added null checks and excluding templates

---

.github/workflows/orch-pr.yaml

Added conditional statement to bypass e2e tests for tenant onboarding.

Added conditional statement to bypass e2e tests for tenant onboarding.

---

.github/workflows/orch-pr.yaml

Changed github var to retrieve upstream repo git branch

Changed github var to retrieve upstream repo git branch

---

.github/workflows/analysis.yaml

fix(analysis): setup .NET 6 and 8

---

.github/workflows/pr.yaml

This is tested https://github.com/GiGInnovationLabs/endeavour-dwh/pull/221

fix(pr): Exclude dwh repo from analysis.

---

.github/workflows/pr.yaml

fix: pr workflow

---

.github/workflows/publish.yaml

feat: added manual publish

---

.github/workflows/publish.yaml

fix(publish): add condition to skip workflow dispatch event

---

.github/workflows/packages.yaml

feat: added package update workflow

---

.github/workflows/orch-pr.yaml

feat: add generated release notes

---

.github/workflows/orch-deploy.yaml

testing RUN https://github.com/GiGInnovationLabs/orch-eks-dev/actions/runs/14885973190/job/41805779294

fix: added downgrade yq step

---

.github/workflows/publish.yaml

Updated `opcr-io/policy` from version `0.1.44`  --> `0.1.47`

feat: opcr io policy update
